# Generated by Django 4.1.6 on 2023-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicier', '0004_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid')], default='unpaid', max_length=200, null=True),
        ),
    ]
